//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a Interference.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:Interference.chug Interference-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:Interference.chug Interference-test.ck -v3`
//--------------------------------------------------------------------

@import "Interference"

// instantiate a Interference
Interference obj => blackhole;;

// call obj.param() with argument of 5; same as obj.param(5)
0.9 => obj.offset;

Step s1(0.) => blackhole;
Step s2(-2.) => blackhole;

s1 => obj.chan(0);
s2 => obj.chan(1);

// print
<<< obj.offset() >>>;
chout <= IO.nl();

for(int i: Std.range(10)) {
  // <<< obj.chan(1).last() >>>;
  <<< obj.last() >>>;  
  samp => now;
}
