//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------
// NOTE by default, chuginate generates a new UGen subclass in this file
//      but it is possible, of course, to create non-UGen classes in a chugin!
// To modify this generated file for a non-UGen class...
//      1. in QUERY->begin_class(), change "UGen" to a different ChucK class
//         (e.g., `QUERY->begin_class(QUERY, "Interference", "Object");`)
//      2. remove or commment out the line containing QUERY->add_ugen_func()
//      3. that's it; the rest is no different for UGens/non-UGens
//-----------------------------------------------------------------------------
// NOTE once you have built this into a chugin (Interference.chug), here are a few
//      helpful tools for testing / probing / verifying your new chugin!
//
// chuginate also generated a Interference-test.ck boilerplate ChucK program
//      to help test your chugin (see Interference-test.ck for more instructions)
//
// run `chuck --chugin-probe` to probe what chugins would be loaded, and
//      from where in the chugin search paths
//
// run `chuck -v3 --loop` to see what chugins are actually loaded at runtime,
//      with more info and error reporting than with --chugin-probe
//
// other helpful chugin-related flags include:
//      --chugin:<filename>
//      --chugin-path:(path) / -G(path)
//      --chugin-load:{on/off}
//
// for more information on command-line options:
//      https://chuck.stanford.edu/doc/program/options.html
// for more information on chugins:
//      https://chuck.stanford.edu/extend/
//-----------------------------------------------------------------------------
// happy chucking & chugging!
//-----------------------------------------------------------------------------

// include chugin header
#include "chugin.h"

// general includes
#include <iostream>


// declaration of chugin constructor
CK_DLL_CTOR(interference_ctor);
// CK_DLL_CTOR(interference_ctor_mod);
CK_DLL_CTOR(interference_ctor_offset);
// CK_DLL_CTOR(interference_ctor_mod_offset);
// declaration of chugin desctructor
CK_DLL_DTOR(interference_dtor);

// example of getter/setter
CK_DLL_MFUN(interference_setOffset);
CK_DLL_MFUN(interference_getOffset);

// CK_DLL_MFUN(interference_setMod);
// CK_DLL_MFUN(interference_getMod);

// for chugins extending UGen, this is mono synthesis function for 1 sample
CK_DLL_TICKF(interference_tick);

// this is a special offset reserved for chugin internal data
t_CKINT interference_data_offset = 0;


//-----------------------------------------------------------------------------
// class definition for internal chugin data
// (NOTE this isn't strictly necessary, but is one example of a recommended approach)
//-----------------------------------------------------------------------------
class Interference
{
public:
  // constructor
  Interference() { m_offset = 0.75; }

  // constructor
  Interference(float offset) { m_offset = offset; }

  Interference( Chuck_Object* mod )
  {
    m_offset = 0.75;
    m_mod = mod;
  }

  Interference( Chuck_Object* mod, float offset )
  {
    m_offset = offset;
    m_mod = mod;
  }

  // for chugins extending UGen
  void tick( SAMPLE * in, SAMPLE * out, t_CKUINT nframes )
  {
    // default: this passes whatever input is patched into chugin
    // return in;

    // if (m_mod == nullptr) {
    //   for (int i; i < nframes; i++) {
    //     out[2*i] = in[0];
    //   }
    //   return;
    // }

    for (int i; i < nframes; i++) {
      float carr_pos = in[0];
      float mod_pos_offset = in[1] + m_offset;

      // std::cout << in[0] << ", " << in[1] << ", " << mod_pos_offset << std::endl;

      if (m_offset >= 0 && mod_pos_offset < in[i]) {
	carr_pos = mod_pos_offset;
      }
      if (m_offset < 0 && mod_pos_offset > in[i]) {
	carr_pos = mod_pos_offset;
      }

      // need to send output to both channels because the mono mixdown signal
      // will average the two channels
      out[2 * i] = carr_pos;
      out[2 * i + 1] = carr_pos;
    }
  }

  // set offseteter example
  t_CKFLOAT setOffset( t_CKFLOAT p )
  {
    m_offset = p;
    return p;
  }

  // get parameter example
  t_CKFLOAT getOffset() { return m_offset; }

  Chuck_Object *setMod(Chuck_Object *mod) {
    m_mod = mod;
    return mod;
  }
  
  Chuck_Object* getMod() { return m_mod; }
  
    
private:
  // instance data
  t_CKFLOAT m_offset;
  Chuck_Object* m_mod; // modulator
};


//-----------------------------------------------------------------------------
// info function: ChucK calls this when loading/probing the chugin
// NOTE: please customize these info fields below; they will be used for
// chugins loading, probing, and package management and documentation
//-----------------------------------------------------------------------------
CK_DLL_INFO( Interference )
{
  // the version string of this chugin, e.g., "v1.2.1"
  QUERY->setinfo( QUERY, CHUGIN_INFO_CHUGIN_VERSION, "" );
  // the author(s) of this chugin, e.g., "Alice Baker & Carl Donut"
  QUERY->setinfo( QUERY, CHUGIN_INFO_AUTHORS, "" );
  // text description of this chugin; what is it? what does it do? who is it for?
  QUERY->setinfo( QUERY, CHUGIN_INFO_DESCRIPTION, "" );
  // (optional) URL of the homepage for this chugin
  QUERY->setinfo( QUERY, CHUGIN_INFO_URL, "" );
  // (optional) contact email
  QUERY->setinfo( QUERY, CHUGIN_INFO_EMAIL, "" );
}


//-----------------------------------------------------------------------------
// query function: ChucK calls this when loading the chugin
// modify this function to define this chugin's API and language extensions
//-----------------------------------------------------------------------------
CK_DLL_QUERY( Interference )
{
  // generally, don't change this...
  QUERY->setname( QUERY, "Interference" );

  // ------------------------------------------------------------------------
  // begin class definition(s); will be compiled, verified,
  // and added to the chuck host type system for use
  // ------------------------------------------------------------------------
  // NOTE to create a non-UGen class, change the second argument
  // to extend a different ChucK class (e.g., "Object")
  QUERY->begin_class( QUERY, "Interference", "UGen" );

  // register default constructor
  QUERY->add_ctor( QUERY, interference_ctor );
  // NOTE constructors can be overloaded like any other functions,
  // each overloaded constructor begins with `QUERY->add_ctor()`
  // followed by a sequence of `QUERY->add_arg()`

  // QUERY->add_ctor(QUERY, interference_ctor_mod);
  // QUERY->add_arg(QUERY, "UGen", "mod");
  
  QUERY->add_ctor(QUERY, interference_ctor_offset);
  QUERY->add_arg(QUERY, "float", "offset");
  
  // QUERY->add_ctor(QUERY, interference_ctor_mod_offset);
  // QUERY->add_arg(QUERY, "UGen", "mod");
  // QUERY->add_arg(QUERY, "float", "offset");

  // register the destructor (probably no need to change)
  QUERY->add_dtor(QUERY, interference_dtor);

  // for UGens only: add tick function
  // NOTE a non-UGen class should remove or comment out this next line
  // input chan 0 is carr, chan 1 is mod
  QUERY->add_ugen_funcf( QUERY, interference_tick, NULL, 2, 1 );
  // NOTE: if this is to be a UGen with more than 1 channel,
  // e.g., a multichannel UGen -- will need to use add_ugen_funcf()
  // and declare a tickf function using CK_DLL_TICKF

  // offset getter and setter
  QUERY->add_mfun( QUERY, interference_setOffset, "float", "offset" );
  QUERY->add_arg( QUERY, "float", "value" );

  QUERY->add_mfun(QUERY, interference_getOffset, "float", "offset");

  // mod getter and setter
  // QUERY->add_mfun(QUERY, interference_setMod, "UGen", "mod");
  // QUERY->add_arg(QUERY, "UGen", "mod");

  // QUERY->add_mfun(QUERY, interference_getMod, "UGen", "mod");
    
  // this reserves a variable in the ChucK internal class to store 
  // referene to the c++ class we defined above
  interference_data_offset = QUERY->add_mvar( QUERY, "int", "@i_data", false );

  // ------------------------------------------------------------------------
  // end the class definition
  // IMPORTANT: this MUST be called to each class definition!
  // ------------------------------------------------------------------------
  QUERY->end_class( QUERY );

  // wasn't that a breeze?
  return TRUE;
}


// implementation for the default constructor
CK_DLL_CTOR( interference_ctor )
{
  // get the offset where we'll store our internal c++ class pointer
  OBJ_MEMBER_INT( SELF, interference_data_offset ) = 0;
    
  // instantiate our internal c++ class representation
  Interference * i_obj = new Interference( );
    
  // store the pointer in the ChucK object member
  OBJ_MEMBER_INT( SELF, interference_data_offset ) = (t_CKINT)i_obj;
}

CK_DLL_CTOR( interference_ctor_offset )
{
  // get the offset where we'll store our internal c++ class pointer
  OBJ_MEMBER_INT(SELF, interference_data_offset) = 0;

  t_CKFLOAT offset = GET_NEXT_FLOAT( ARGS );
    
  // instantiate our internal c++ class representation
  Interference *i_obj = new Interference(offset);
    
  // store the pointer in the ChucK object member
  OBJ_MEMBER_INT( SELF, interference_data_offset ) = (t_CKINT)i_obj;
}


// implementation for the destructor
CK_DLL_DTOR( interference_dtor )
{
  // get our c++ class pointer
  Interference * i_obj = (Interference *)OBJ_MEMBER_INT( SELF, interference_data_offset );
  // clean up (this macro tests for NULL, deletes, and zeros out the variable)
  CK_SAFE_DELETE( i_obj );
  // set the data field to 0
  OBJ_MEMBER_INT( SELF, interference_data_offset ) = 0;
}


// implementation for tick function (relevant only for UGens)
CK_DLL_TICKF( interference_tick )
{
  // get our c++ class pointer
  Interference * i_obj = (Interference *)OBJ_MEMBER_INT(SELF, interference_data_offset);
 
  // invoke our tick function; store in the magical out variable
  if (i_obj)
    i_obj->tick(in, out, nframes);

  // yes
  return TRUE;
}


// example implementation for setter
CK_DLL_MFUN( interference_setOffset )
{
  // get our c++ class pointer
  Interference * i_obj = (Interference *)OBJ_MEMBER_INT( SELF, interference_data_offset );

  // get next argument
  // NOTE argument type must match what is specified above in CK_DLL_QUERY
  // NOTE this advances the ARGS pointer, so save in variable for re-use
  t_CKFLOAT arg1 = GET_NEXT_FLOAT( ARGS );
    
  // call setOffset() and set the return value
  RETURN->v_float = i_obj->setOffset( arg1 );
}


// example implementation for getter
CK_DLL_MFUN(interference_getOffset)
{
  // get our c++ class pointer
  Interference * i_obj = (Interference *)OBJ_MEMBER_INT( SELF, interference_data_offset );

  // call getOffset() and set the return value
  RETURN->v_float = i_obj->getOffset();
}


// CK_DLL_MFUN( interference_setMod )
// {
//   // get our c++ class pointer
//   Interference * i_obj = (Interference *)OBJ_MEMBER_INT( SELF, interference_data_offset );

//   // get next argument
//   // NOTE argument type must match what is specified above in CK_DLL_QUERY
//   // NOTE this advances the ARGS pointer, so save in variable for re-use
//   Chuck_Object * mod = (Chuck_Object *)GET_NEXT_OBJECT(ARGS);
    
//   // call setOffset() and set the return value
//   RETURN->v_float = i_obj->setOffset( arg1 );
// }


// CK_DLL_MFUN(interference_getMod)
// {
//   // get our c++ class pointer
//   Interference * i_obj = (Interference *)OBJ_MEMBER_INT( SELF, interference_data_offset );

//   // call getOffset() and set the return value
//   RETURN->v_float = i_obj->getOffset();
// }
